In [ ]:
class grandparent:
    def gp (self):
        print("This is Grand Parent.")
class Parent (grandparent):
    def f1 (self):
        print("This is parent class.")
class Child (Parent):
    def f2 (self):
        print("This is child class.")
ob = Parent()
ob.f2()
ob.f1()
ob.gp()

In [ ]:
# multiple inheritance.
class parent1:
    def f2 (self):
        print("This is parent 1")
class parent2:
    def f1 (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.f1()
ob.f2()

In [ ]:
# over riding.
class parent1:
    def f2 (self):
        print("This is parent 1")
class parent2:
    def f (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        super().f()
        print("This is child")
ob = child()
ob.f()
ob.f2()

In [ ]:
# over riding.
class parent1:
    def f2 (self):
        print("This is parent 1")
class parent2:
    def f (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        parent2.f(self)
        print("This is child")
ob = child()
ob.f()
ob.f2()

In [ ]:
# over riding.
class parent1:
    def p1 (self):
        print("This is parent 1")
class parent2:
    def p1 (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.p1()

In [ ]:
# over riding.
class parent1:
    def p1 (self):
        print("This is parent 1")
class parent2:
    def p1 (self):
        print("This is parent 2")
class child (parent2,parent1):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.p1()

In [ ]:
# over riding.
class parent1:
    def p1 (self):
        print("This is parent 1")
class parent2:
    def p1 (self):
        print("This is parent 2")
class child (parent2,parent1):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.p1()
print(child.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    def t1 (self):
        print("This is Class A")
class B (A):
    def t1 (self):
        print("This is Class B")
class C:
    def t1 (self):
        print("This is Class C")
class D (B,C):
    def t (self):
        print("This is Class D")
ob = D()
ob.t()
ob.t1()
print(D.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    pass
class B:
    pass
class C (A,B):
    pass
class D (B):
    pass
class E (C,D):
    pass
ob = E()
print(E.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    pass
class B:
    pass
class C (A,B):
    pass
class D (A):
    pass
class E (C,D):
    pass
ob = E()
print(E.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    pass
class B:
    pass
class C (A,B):
    pass
class D (B):
    pass
class E (C,D,B):
    pass
ob = E()
print(E.__mro__)

In [ ]:
# PB (610) :-
class P:
    pass
class Q:
    pass
class R(P,Q):
    pass
class S(Q):
    pass     
class T(S,R):
    pass
a=T()
print(T.__mro__)

In [ ]:
class A:
    def f1 (self):
        print("class A")
class B:
    def f1 (self):
        print("class B")
class C (A,B):
    def f1 (self):
        super().f1()
        B.f1(self)
        print("Class C")
ob = C()
ob.f1()

In [ ]:
# Hierarchical inheritance.
class A:
    def f1 (self):
        print("class A")
class B (A):
    def c1 (self):
        print("child 1")
class C (A):
    def c2 (self):
        print("child 2")
ob = B()
ob.c1()
ob.f1()

ok = C()
ok.c2()
ok.f1()

print(issubclass(B,A))
print(isinstance(ob,A))

In [ ]:
# PB (633) :-
'''
Implement the following hierarchy . The Staff function has name and salary as its data members, 
the derived class Teaching has subject as its data member and the class NonTeaching has 
department as its data member. The derived class method overrides (extends) the methods of the base class.
'''
class Staff:
    def __init__(self,name,salary):
        self.name = name
        self.salary = salary
    def dis(self):
        print("Name :",self.name)
        print("Salary :",self.salary)
class Teaching (Staff):
    def __init__(self, name, salary, subject):
        print("-: Teaching :-")
        super().__init__(name,salary)
        self.subject = subject
    def dis (self):
        super().dis()
        print("Subject :",self.subject)
class NonTeaching (Staff):
    def __init__(self, name, salary, sub):
        print("-: Non Teaching :-")
        super().__init__(name, salary)
        self.sub = sub
    def dis (self):
        super().dis()
        print("Subject :",self.sub)
ob = Teaching("A",50000,"JAVA")
ob.dis()
ob1 = NonTeaching("B",30000,"Digital Marketing")
ob1.dis()

# Operator Overloading
#### 1. Airthmetic Operator :-
##### __add__(+)
##### __sub__(-)
##### __mul__(*)
##### __truediv__(/)
##### __floordiv__(//)
##### __mod__(%)
##### __pow__(**)

#### 2. Comperision Operator :-
##### __lt__(<)
##### __gt__(>)
##### __le__(<=)
##### __ge__(>=)
##### __eq__(==)
##### __ne__(!=)

In [ ]:
# Comparision Operator
class Cl:
    def __init__(self,x):
        self.x = x
    def __lt__(self,other):
        if(self.x < other.x):
            print(other.x,"is Big")
        else:
            print(other.x,"is Small")
    def __gt__(self,other):
        if(self.x > other.x):
            print(other.x,"is Small")
        else:
            print(other.x,"is Big")
    def __le__(self,other):
        if(self.x <= other.x):
            print(other.x,"is Big or Equal")
        else:
            print(other.x,"is Small")
    def __ge__(self,other):
        if(self.x >= other.x):
            print(other.x,"is Less or Equal")
        else:
            print(other.x,"is Big")
    def __eq__(self,other):
        if(self.x == other.x):
            print(other.x,"Both Equal")
        else:
            print(other.x,"Not Equal")
    def __ne__(self,other):
        if(self.x != other.x):
            print(other.x,"Not Equal")
        else:
            print(other.x,"Both Equal")
ob = Cl(10)
ob1 = Cl(20)
ob>ob1
ob==ob1
ob<ob1

In [ ]:
# Arithmetic Operator
class Cl:
    def __init__(self,x):
        self.x = x
    def __add__(self,other):
        return self.x + other.x
    def __sub__(self,other):
        return self.x - other.x
    def __mul__(self,other):
        return self.x * other.x
    def __truediv__(self,other):
        return self.x / other.x
    def __floordiv__(self,other):
        return self.x // other.x
    def __mod__(self,other):
        return self.x % other.x
    def __pow__(self,other):
        return self.x ** other.x
ob = Cl(10)
ob1 = Cl(20)
print("Ans is: ",ob*ob1)

In [ ]:
class Stu:
    s = []
    def __init__(self,rno,name,age,total):
        self.rno = rno
        self.name = name
        self.age = age
        self.total = total
        Stu.s.append(self)
    def __eq__(self, value):
        if(self.total == value.total):
            print(self.name," Has same mark as",value.name)
ob = Stu(10,"Kishan",18,90)
ob = Stu(11,"Jyot",18,100)
ob = Stu(12,"Trushangi",18,90)
for i in range(len(Stu.s)):
    for j in range(i+1,len(Stu.s)):
        Stu.s[i] == Stu.s[j]


In [ ]:
# Abstraction in 'python'


# NumPy :-

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

In [ ]:
import numpy as np
arr = np.array((10,20,30))
print(arr)
print(type(arr))

In [ ]:
import numpy as np
arr = np.array({"kishan","patel"})
print(arr)
print(type(arr))

In [ ]:
import numpy as np
arr = np.array({"kishan":"patel","karan":"trivedi"})
print(arr)
print(type(arr))

## Numpy array dimentions :- (0d,1d,2d,..)

In [ ]:
# 0D array
import numpy as np
arr = np.array(25)
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
# 1D array
import numpy as np
arr = np.array([25,30,35])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
# 2D array
import numpy as np
arr = np.array([[20,30,40],[50,60,70],[80,90,100]])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
import numpy as np
arr = np.array([[20,30],[50,60],[80,90]])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
# 3D array
import numpy as np
arr = np.array([[[20,30,40],[50,60,70],[80,90,100]],[[20,30,40],[50,60,70],[80,90,100]],[[20,30,40],[50,60,70],[80,90,100]]])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
# 6D array
import numpy as np
arr = np.array([80,90,100],ndmin=6) # this is used to define manual dimention like, 1D,2D,3D
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
import numpy as np
arr = np.array([[80,90,100],[80,90,100]],ndmin=6) # this is used to define manual dimention like, 1D,2D,3D
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

In [ ]:
import numpy as np
arr = np.array([[80,90],[80,90]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,4)
print(arr)
print("New :",arr.shape)

In [ ]:
import numpy as np
arr = np.array([[80,90],[80,90],[3,4]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,3,2)
print(arr)
print("New :",arr.shape)

In [ ]:
import numpy as np
arr = np.array([[80,90],[80,90]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,2)
print(arr)
print("New :",arr.shape)

In [ ]:
import numpy as np
arr = np.array([[80,90],[80,90]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,2,1,2)
print(arr)
print("New :",arr.shape)

-> To reshape an array, you must have the exact number of elements required for the new shape.

In [ ]:
import numpy as np
arr = np.array(range(1,151)).reshape(5,2,3,5) # 5 is column 3 is row
print(arr)

In [ ]:
import numpy as np
arr = np.array(range(1,121)).reshape(5,4,6)
# print(arr)
for m in range(len(arr)):
    for row in range(len(arr[m])):
        arr[m][row][2] *= 100
print(arr)

In [ ]:
import numpy as np
arr = np.array(range(1,121)).reshape(5,4,6)
# print(arr)
for m in range(len(arr)):
    for row in range(len(arr[m])):
        arr[m][row][1::2] = 0
print(arr)

## Slicing in Numpy :-
- Slicing in 

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3, 1:4])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[::2, ::3])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3, ::2])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3, ::-2])

In [ ]:
import numpy as np
'''
[[ 2  5  8]
 [26 29 32]]
'''
arr = np.array(range(1,41)).reshape(5,8)
print(arr)
ans = arr[0::3, 1::3]
print()
print(ans)

In [ ]:
import numpy as np
'''
[[  2   5]
 [ 50  53]
 [ 98 101]
 [146 149]
 [194 197]]
'''
arr = np.array(range(1,241)).reshape(5,8,6)
# print(arr)
print()
ans = arr[0::1, 0, 1::3]
print(ans)

In [ ]:
import numpy as np
'''
[[ 3 45 ]
 [ 147 189 ]]
'''
arr = np.array(range(1,241)).reshape(5,8,6)
# print(arr)
print()
ans = arr[0::3, 0::7, 2]
print(ans)

In [ ]:
# Flating the array. (making one dimention array from any dimention)
arr = np.array(range(1,241)).reshape(5,8,6)
ans = arr.reshape(-1)
print(ans)

In [ ]:
from abc import ABC, abstractmethod
class parent(ABC):
    @abstractmethod
    def printing(self,value):
        print("This is Value from child :",value)
class child(parent):
    def printing(self,value):
        return super().printing(value)
ob = child()
name = input("Enter name : ")
ob.printing(name)

In [2]:
import numpy as np
a1 = np.array([10,20])
a2 = np.array([30,40])
a3 = np.array([50,60])
a4 = np.array([70,80])
arr = np.concatenate((a1,a2,a3,a4))
print(arr)

[10 20 30 40 50 60 70 80]


## concatenate :-
-> we can merge 1 or more direction array using ' concatenate()  method

In [6]:
import numpy as np
a1 = np.array([[10,20],[30,40],[50,60]])
a2 = np.array([[70,80],[90,100],[110,120]])
arr = np.concatenate((a1,a2))
print(arr)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]]


In [7]:
import numpy as np
a1 = np.array([[10,20],[30,40],[50,60]])
a2 = np.array([[70,80],[90,100],[110,120]])
arr = np.concatenate((a1,a2), axis=1)
print(arr)

[[ 10  20  70  80]
 [ 30  40  90 100]
 [ 50  60 110 120]]


In [9]:
import numpy as np
a1 = np.array([[10,20],[30,40],[50,60]])
a2 = np.array([[70,80],[90,100]])
arr = np.concatenate((a1,a2), axis=0)
print(arr)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [21]:
# 3D merging
import numpy as np
a1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
arr = np.concatenate((a1,a2), axis=0)
print(arr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
(4, 2, 2)


In [20]:
# 3D merging
import numpy as np
a1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
arr = np.concatenate((a1,a2), axis=1)
print(arr)
print(arr.shape)

[[[ 1  2]
  [ 3  4]
  [10 20]
  [30 40]]

 [[ 5  6]
  [ 7  8]
  [50 60]
  [70 80]]]
(2, 4, 2)


In [19]:
# 3D merging
import numpy as np
a1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a2 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
arr = np.concatenate((a1,a2), axis=2)
print(arr)
print(arr.shape)

[[[ 1  2 10 20]
  [ 3  4 30 40]]

 [[ 5  6 50 60]
  [ 7  8 70 80]]]
(2, 2, 4)


## split method:- array_split()

In [26]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,3)
print(n)
print()
for i in n:
    print(i)

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]
[3 4]
[5 6]


In [27]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,2)
print(n)
print()
for i in n:
    print(i)

[array([1, 2, 3]), array([4, 5, 6])]

[1 2 3]
[4 5 6]


In [28]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,4)
print(n)
print()
for i in n:
    print(i)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

[1 2]
[3 4]
[5]
[6]


In [29]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,5)
print(n)
print()
for i in n:
    print(i)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

[1 2]
[3]
[4]
[5]
[6]


In [30]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,6)
print(n)
print()
for i in n:
    print(i)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

[1]
[2]
[3]
[4]
[5]
[6]


In [31]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,7)
print(n)
print()
for i in n:
    print(i)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]

[1]
[2]
[3]
[4]
[5]
[6]
[]


In [34]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,8)
print(n)
print()
for i in n:
    print(i)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64)]

[1]
[2]
[3]
[4]
[5]
[6]
[]
[]


In [33]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,4)
print(n[2])
print(n[1])
print()
for i in n:
    print(i)

[5]
[3 4]

[1 2]
[3 4]
[5]
[6]


In [35]:
import numpy as np
a = np.array([1,2,3,4,5,6])
n = np.array_split(a,8)
print(n)
print()
for i in n:
    print(i)
    print("*******")

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64)]

[1]
*******
[2]
*******
[3]
*******
[4]
*******
[5]
*******
[6]
*******
[]
*******
[]
*******


In [38]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
n = np.array_split(a,1)
print(n)
print()
for i in n:
    print(i)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [39]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
n = np.array_split(a,2)
print(n)
print()
for i in n:
    print(i)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]


In [40]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
n = np.array_split(a,3)
print(n)
print()
for i in n:
    print(i)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([], shape=(0, 6), dtype=int64)]

[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]
[]


In [41]:
import numpy as np
a = np.array(range(1,13)).reshape(3,4)
n = np.array_split(a,2,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [42]:
import numpy as np
a = np.array(range(1,13)).reshape(3,4)
n = np.array_split(a,1,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
import numpy as np
a = np.array(range(1,13)).reshape(3,4)
n = np.array_split(a,4,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]

[[1]
 [5]
 [9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]
[[ 4]
 [ 8]
 [12]]


In [ ]:
import numpy as np
a = np.array(range(1,13)).reshape(3,4)
n = np.array_split(a,6,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]]), array([], shape=(3, 0), dtype=int64), array([], shape=(3, 0), dtype=int64)]

[[1]
 [5]
 [9]]
[[ 2]
 [ 6]
 [10]]
[[ 3]
 [ 7]
 [11]]
[[ 4]
 [ 8]
 [12]]
[]
[]


In [47]:
import numpy as np
a = np.array(range(1,25)).reshape(4,2,3)
n = np.array_split(a,2,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[[ 1,  2,  3]],

       [[ 7,  8,  9]],

       [[13, 14, 15]],

       [[19, 20, 21]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]],

       [[16, 17, 18]],

       [[22, 23, 24]]])]

[[[ 1  2  3]]

 [[ 7  8  9]]

 [[13 14 15]]

 [[19 20 21]]]
[[[ 4  5  6]]

 [[10 11 12]]

 [[16 17 18]]

 [[22 23 24]]]


In [48]:
import numpy as np
a = np.array(range(1,25)).reshape(4,2,3)
n = np.array_split(a,3,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[[ 1,  2,  3]],

       [[ 7,  8,  9]],

       [[13, 14, 15]],

       [[19, 20, 21]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]],

       [[16, 17, 18]],

       [[22, 23, 24]]]), array([], shape=(4, 0, 3), dtype=int64)]

[[[ 1  2  3]]

 [[ 7  8  9]]

 [[13 14 15]]

 [[19 20 21]]]
[[[ 4  5  6]]

 [[10 11 12]]

 [[16 17 18]]

 [[22 23 24]]]
[]


In [49]:
import numpy as np
a = np.array(range(1,25)).reshape(4,2,3)
n = np.array_split(a,4,axis=1)
print(n)
print()
for i in n:
    print(i)

[array([[[ 1,  2,  3]],

       [[ 7,  8,  9]],

       [[13, 14, 15]],

       [[19, 20, 21]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]],

       [[16, 17, 18]],

       [[22, 23, 24]]]), array([], shape=(4, 0, 3), dtype=int64), array([], shape=(4, 0, 3), dtype=int64)]

[[[ 1  2  3]]

 [[ 7  8  9]]

 [[13 14 15]]

 [[19 20 21]]]
[[[ 4  5  6]]

 [[10 11 12]]

 [[16 17 18]]

 [[22 23 24]]]
[]
[]


## where method :- where()
-> it will find according given condetion and return array of indexes according given condetion

In [52]:
import numpy as np
a = np.array([1,2,4,3,4,5,6,4])
n = np.where(a==4)
print(n)

(array([2, 4, 7]),)


In [53]:
import numpy as np
a = np.array([1,2,4,3,4,5,6,4])
n = np.where(a%2 == 0)
print(n)

(array([1, 2, 4, 6, 7]),)


In [57]:
# where method for 2D
import numpy as np
a = np.array([[1,2],[4,3],[4,5],[6,4]])
n = np.where(a == 4)
print(n)
for i in n:
    print(i)

(array([1, 2, 3]), array([0, 0, 1]))
[1 2 3]
[0 0 1]


In [58]:
# where method for 2D
import numpy as np
a = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60],[65,70,75]])
n = np.where(a%3 == 0)
print(n)
for i in n:
    print(i)

(array([0, 1, 2, 3, 4]), array([2, 2, 2, 2, 2]))
[0 1 2 3 4]
[2 2 2 2 2]


In [59]:
# where method for 2D
import numpy as np
a = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60],[65,70,75]])
n = np.where(a%2 == 0)
print(n)
for i in n:
    print(i)

(array([0, 1, 1, 2, 3, 3, 4]), array([1, 0, 2, 1, 0, 2, 1]))
[0 1 1 2 3 3 4]
[1 0 2 1 0 2 1]


In [60]:
# where method for 2D
import numpy as np
a = np.array([[[5,10,15],[20,25,30]],[[35,40,45],[50,55,60]],[[65,70,75],[80,85,90]]])
n = np.where(a%2 == 0)
print(n)
for i in n:
    print(i)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 1, 0, 1, 1, 0, 1, 1]), array([1, 0, 2, 1, 0, 2, 1, 0, 2]))
[0 0 0 1 1 1 2 2 2]
[0 1 1 0 1 1 0 1 1]
[1 0 2 1 0 2 1 0 2]


## sorting in array :- sort()

In [ ]:
import numpy as np
a = np.array([3,0,2,1])
x = np.sort(a)[::-1]
print(x) # it will print array in reverse order

[3 2 1 0]


In [ ]:
import numpy as np
a = np.array([[12,1],[3,7]])
x = np.sort(a, axis=0)
print(x)

[[ 3  1]
 [12  7]]


In [71]:
import numpy as np
a = np.array([1,2,3])
print(a+5)

[6 7 8]


In [72]:
import numpy as np
a = np.array([1,2,3])
a1 = np.array([10,20,30])
print(a+a1)

[11 22 33]


In [73]:
import numpy as np
a = np.array([1,2,3])
a1 = np.array([10,20])
print(a+a1)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [74]:
import numpy as np
a = np.array([1,2,3])
print(a*2)

[2 4 6]


In [75]:
import numpy as np
a = np.array([1,2,3])
print(a**2)

[1 4 9]
