In [ ]:
class grandparent:
    def gp (self):
        print("This is Grand Parent.")
class Parent (grandparent):
    def f1 (self):
        print("This is parent class.")
class Child (Parent):
    def f2 (self):
        print("This is child class.")
ob = Parent()
ob.f2()
ob.f1()
ob.gp()

In [ ]:
# multiple inheritance.
class parent1:
    def f2 (self):
        print("This is parent 1")
class parent2:
    def f1 (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.f1()
ob.f2()

In [ ]:
# over riding.
class parent1:
    def f2 (self):
        print("This is parent 1")
class parent2:
    def f (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        super().f()
        print("This is child")
ob = child()
ob.f()
ob.f2()

In [ ]:
# over riding.
class parent1:
    def f2 (self):
        print("This is parent 1")
class parent2:
    def f (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        parent2.f(self)
        print("This is child")
ob = child()
ob.f()
ob.f2()

In [ ]:
# over riding.
class parent1:
    def p1 (self):
        print("This is parent 1")
class parent2:
    def p1 (self):
        print("This is parent 2")
class child (parent1,parent2):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.p1()

In [ ]:
# over riding.
class parent1:
    def p1 (self):
        print("This is parent 1")
class parent2:
    def p1 (self):
        print("This is parent 2")
class child (parent2,parent1):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.p1()

In [ ]:
# over riding.
class parent1:
    def p1 (self):
        print("This is parent 1")
class parent2:
    def p1 (self):
        print("This is parent 2")
class child (parent2,parent1):
    def f (self):
        print("This is child")
ob = child()
ob.f()
ob.p1()
print(child.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    def t1 (self):
        print("This is Class A")
class B (A):
    def t1 (self):
        print("This is Class B")
class C:
    def t1 (self):
        print("This is Class C")
class D (B,C):
    def t (self):
        print("This is Class D")
ob = D()
ob.t()
ob.t1()
print(D.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    pass
class B:
    pass
class C (A,B):
    pass
class D (B):
    pass
class E (C,D):
    pass
ob = E()
print(E.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    pass
class B:
    pass
class C (A,B):
    pass
class D (A):
    pass
class E (C,D):
    pass
ob = E()
print(E.__mro__)

In [ ]:
# MRO (method resolution order)
class A:
    pass
class B:
    pass
class C (A,B):
    pass
class D (B):
    pass
class E (C,D,B):
    pass
ob = E()
print(E.__mro__)

In [ ]:
# PB (610) :-
class P:
    pass
class Q:
    pass
class R(P,Q):
    pass
class S(Q):
    pass     
class T(S,R):
    pass
a=T()
print(T.__mro__)

In [ ]:
class A:
    def f1 (self):
        print("class A")
class B:
    def f1 (self):
        print("class B")
class C (A,B):
    def f1 (self):
        super().f1()
        B.f1(self)
        print("Class C")
ob = C()
ob.f1()

In [ ]:
# Hierarchical inheritance.
class A:
    def f1 (self):
        print("class A")
class B (A):
    def c1 (self):
        print("child 1")
class C (A):
    def c2 (self):
        print("child 2")
ob = B()
ob.c1()
ob.f1()

ok = C()
ok.c2()
ok.f1()

print(issubclass(B,A))
print(isinstance(ob,A))

In [ ]:
# PB (633) :-
'''
Implement the following hierarchy . The Staff function has name and salary as its data members, 
the derived class Teaching has subject as its data member and the class NonTeaching has 
department as its data member. The derived class method overrides (extends) the methods of the base class.
'''
class Staff:
    def __init__(self,name,salary):
        self.name = name
        self.salary = salary
    def dis(self):
        print("Name :",self.name)
        print("Salary :",self.salary)
class Teaching (Staff):
    def __init__(self, name, salary, subject):
        print("-: Teaching :-")
        super().__init__(name,salary)
        self.subject = subject
    def dis (self):
        super().dis()
        print("Subject :",self.subject)
class NonTeaching (Staff):
    def __init__(self, name, salary, sub):
        print("-: Non Teaching :-")
        super().__init__(name, salary)
        self.sub = sub
    def dis (self):
        super().dis()
        print("Subject :",self.sub)
ob = Teaching("A",50000,"JAVA")
ob.dis()
ob1 = NonTeaching("B",30000,"Digital Marketing")
ob1.dis()

# Operator Overloading
#### 1. Airthmetic Operator :-
##### __add__(+)
##### __sub__(-)
##### __mul__(*)
##### __truediv__(/)
##### __floordiv__(//)
##### __mod__(%)
##### __pow__(**)

#### 2. Comperision Operator :-
##### __lt__(<)
##### __gt__(>)
##### __le__(<=)
##### __ge__(>=)
##### __eq__(==)
##### __ne__(!=)

In [6]:
# Comparision Operator
class Cl:
    def __init__(self,x):
        self.x = x
    def __lt__(self,other):
        if(self.x < other.x):
            print(other.x,"is Big")
        else:
            print(other.x,"is Small")
    def __gt__(self,other):
        if(self.x > other.x):
            print(other.x,"is Small")
        else:
            print(other.x,"is Big")
    def __le__(self,other):
        if(self.x <= other.x):
            print(other.x,"is Big or Equal")
        else:
            print(other.x,"is Small")
    def __ge__(self,other):
        if(self.x >= other.x):
            print(other.x,"is Less or Equal")
        else:
            print(other.x,"is Big")
    def __eq__(self,other):
        if(self.x == other.x):
            print(other.x,"Both Equal")
        else:
            print(other.x,"Not Equal")
    def __ne__(self,other):
        if(self.x != other.x):
            print(other.x,"Not Equal")
        else:
            print(other.x,"Both Equal")
ob = Cl(10)
ob1 = Cl(20)
ob>ob1
ob==ob1
ob<ob1

20 is Big
20 Not Equal
20 is Big


In [ ]:
# Arithmetic Operator
class Cl:
    def __init__(self,x):
        self.x = x
    def __add__(self,other):
        return self.x + other.x
    def __sub__(self,other):
        return self.x - other.x
    def __mul__(self,other):
        return self.x * other.x
    def __truediv__(self,other):
        return self.x / other.x
    def __floordiv__(self,other):
        return self.x // other.x
    def __mod__(self,other):
        return self.x % other.x
    def __pow__(self,other):
        return self.x ** other.x
ob = Cl(10)
ob1 = Cl(20)
print("Ans is: ",ob*ob1)

In [12]:
class Stu:
    s = []
    def __init__(self,rno,name,age,total):
        self.rno = rno
        self.name = name
        self.age = age
        self.total = total
        Stu.s.append(self)
    def __eq__(self, value):
        if(self.total == value.total):
            print(self.name," Has same mark as",value.name)
ob = Stu(10,"Kishan",18,90)
ob = Stu(11,"Jyot",18,100)
ob = Stu(12,"Trushangi",18,90)
for i in range(len(Stu.s)):
    for j in range(i+1,len(Stu.s)):
        Stu.s[i] == Stu.s[j]


Kishan  Has same mark as Trushangi


In [14]:
# Abstraction in 'python'


# NumPy :-

In [3]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array((10,20,30))
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr = np.array({"kishan","patel"})
print(arr)
print(type(arr))

{'kishan', 'patel'}
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr = np.array({"kishan":"patel","karan":"trivedi"})
print(arr)
print(type(arr))

{'kishan': 'patel', 'karan': 'trivedi'}
<class 'numpy.ndarray'>


## Numpy array dimentions :- (0d,1d,2d,..)

In [ ]:
# 0D array
import numpy as np
arr = np.array(25)
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

25
Dimention:  0
Shape:  ()


In [ ]:
# 1D array
import numpy as np
arr = np.array([25,30,35])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

[25 30 35]
Dimention:  1
Shape:  (3,)


In [ ]:
# 2D array
import numpy as np
arr = np.array([[20,30,40],[50,60,70],[80,90,100]])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]
Dimention:  2
Shape:  (3, 3)


In [14]:
import numpy as np
arr = np.array([[20,30],[50,60],[80,90]])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

[[20 30]
 [50 60]
 [80 90]]
Dimention:  2
Shape:  (3, 2)


In [18]:
# 3D array
import numpy as np
arr = np.array([[[20,30,40],[50,60,70],[80,90,100]],[[20,30,40],[50,60,70],[80,90,100]],[[20,30,40],[50,60,70],[80,90,100]]])
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

[[[ 20  30  40]
  [ 50  60  70]
  [ 80  90 100]]

 [[ 20  30  40]
  [ 50  60  70]
  [ 80  90 100]]

 [[ 20  30  40]
  [ 50  60  70]
  [ 80  90 100]]]
Dimention:  3
Shape:  (3, 3, 3)


In [ ]:
# 6D array
import numpy as np
arr = np.array([80,90,100],ndmin=6) # this is used to define manual dimention like, 1D,2D,3D
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

[[[[[[ 80  90 100]]]]]]
Dimention:  6
Shape:  (1, 1, 1, 1, 1, 3)


In [20]:
import numpy as np
arr = np.array([[80,90,100],[80,90,100]],ndmin=6) # this is used to define manual dimention like, 1D,2D,3D
print(arr)
print("Dimention: ",arr.ndim)
print("Shape: ",arr.shape)

[[[[[[ 80  90 100]
     [ 80  90 100]]]]]]
Dimention:  6
Shape:  (1, 1, 1, 1, 2, 3)


In [22]:
import numpy as np
arr = np.array([[80,90],[80,90]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,4)
print(arr)
print("New :",arr.shape)

[[80 90]
 [80 90]]
Old : (2, 2)
[[80 90 80 90]]
New : (1, 4)


In [27]:
import numpy as np
arr = np.array([[80,90],[80,90],[3,4]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,3,2)
print(arr)
print("New :",arr.shape)

[[80 90]
 [80 90]
 [ 3  4]]
Old : (3, 2)
[[[80 90]
  [80 90]
  [ 3  4]]]
New : (1, 3, 2)


In [30]:
import numpy as np
arr = np.array([[80,90],[80,90]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,2)
print(arr)
print("New :",arr.shape)

[[80 90]
 [80 90]]
Old : (2, 2)


ValueError: cannot reshape array of size 4 into shape (1,2)

In [31]:
import numpy as np
arr = np.array([[80,90],[80,90]]) 
print(arr)
print("Old :",arr.shape)
arr = arr.reshape(1,2,1,2)
print(arr)
print("New :",arr.shape)

[[80 90]
 [80 90]]
Old : (2, 2)
[[[[80 90]]

  [[80 90]]]]
New : (1, 2, 1, 2)


-> To reshape an array, you must have the exact number of elements required for the new shape.

In [ ]:
import numpy as np
arr = np.array(range(1,151)).reshape(5,2,3,5) # 5 is column 3 is row
print(arr)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]]

  [[ 16  17  18  19  20]
   [ 21  22  23  24  25]
   [ 26  27  28  29  30]]]


 [[[ 31  32  33  34  35]
   [ 36  37  38  39  40]
   [ 41  42  43  44  45]]

  [[ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]]

  [[ 76  77  78  79  80]
   [ 81  82  83  84  85]
   [ 86  87  88  89  90]]]


 [[[ 91  92  93  94  95]
   [ 96  97  98  99 100]
   [101 102 103 104 105]]

  [[106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]


 [[[121 122 123 124 125]
   [126 127 128 129 130]
   [131 132 133 134 135]]

  [[136 137 138 139 140]
   [141 142 143 144 145]
   [146 147 148 149 150]]]]


In [44]:
import numpy as np
arr = np.array(range(1,121)).reshape(5,4,6)
# print(arr)
for m in range(len(arr)):
    for row in range(len(arr[m])):
        arr[m][row][2] *= 100
print(arr)

[[[    1     2   300     4     5     6]
  [    7     8   900    10    11    12]
  [   13    14  1500    16    17    18]
  [   19    20  2100    22    23    24]]

 [[   25    26  2700    28    29    30]
  [   31    32  3300    34    35    36]
  [   37    38  3900    40    41    42]
  [   43    44  4500    46    47    48]]

 [[   49    50  5100    52    53    54]
  [   55    56  5700    58    59    60]
  [   61    62  6300    64    65    66]
  [   67    68  6900    70    71    72]]

 [[   73    74  7500    76    77    78]
  [   79    80  8100    82    83    84]
  [   85    86  8700    88    89    90]
  [   91    92  9300    94    95    96]]

 [[   97    98  9900   100   101   102]
  [  103   104 10500   106   107   108]
  [  109   110 11100   112   113   114]
  [  115   116 11700   118   119   120]]]


In [47]:
import numpy as np
arr = np.array(range(1,121)).reshape(5,4,6)
# print(arr)
for m in range(len(arr)):
    for row in range(len(arr[m])):
        arr[m][row][1::2] = 0
print(arr)

[[[  1   0   3   0   5   0]
  [  7   0   9   0  11   0]
  [ 13   0  15   0  17   0]
  [ 19   0  21   0  23   0]]

 [[ 25   0  27   0  29   0]
  [ 31   0  33   0  35   0]
  [ 37   0  39   0  41   0]
  [ 43   0  45   0  47   0]]

 [[ 49   0  51   0  53   0]
  [ 55   0  57   0  59   0]
  [ 61   0  63   0  65   0]
  [ 67   0  69   0  71   0]]

 [[ 73   0  75   0  77   0]
  [ 79   0  81   0  83   0]
  [ 85   0  87   0  89   0]
  [ 91   0  93   0  95   0]]

 [[ 97   0  99   0 101   0]
  [103   0 105   0 107   0]
  [109   0 111   0 113   0]
  [115   0 117   0 119   0]]]


## Slicing in Numpy :-
- Slicing in 

In [51]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [52]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [53]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3, 1:4])

[[ 7  8  9]
 [17 18 19]]


In [54]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[::2, ::3])

[[ 1  4]
 [16 19]]


In [55]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3, ::2])

[[ 6  8 10]
 [16 18 20]]


In [56]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,20]])
print(arr[1:3, ::-2])

[[10  8  6]
 [20 18 16]]


In [ ]:
import numpy as np
'''
[[ 2  5  8]
 [26 29 32]]
'''
arr = np.array(range(1,41)).reshape(5,8)
print(arr)
ans = arr[0::3, 1::3]
print()
print(ans)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]

[[ 2  5  8]
 [26 29 32]]


In [ ]:
import numpy as np
'''
[[  2   5]
 [ 50  53]
 [ 98 101]
 [146 149]
 [194 197]]
'''
arr = np.array(range(1,241)).reshape(5,8,6)
# print(arr)
print()
ans = arr[0::1, 0, 1::3]
print(ans)


[[  2   5]
 [ 50  53]
 [ 98 101]
 [146 149]
 [194 197]]


In [ ]:
import numpy as np
'''
[[ 3 45 ]
 [ 147 189 ]]
'''
arr = np.array(range(1,241)).reshape(5,8,6)
# print(arr)
print()
ans = arr[0::3, 0::7, 2]
print(ans)


[[  3  45]
 [147 189]]
